name: lgrun_n

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
   Run:
    runs-on: ubuntu-latest

    steps:
     - name: Set up Python 3.8
       uses: actions/setup-python@v2
       with:
          python-version: 3.8

     - name: Testing repo
       uses: actions/checkout@v2
       with:
          repository: pykancha/reddit-bots
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          refs: master
          path: app

     - name: Credentials repo
       uses: actions/checkout@v2
       with:
          repository: hemanta212/personal
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          refs: master
          path: personal
       
     - name: Data repo
       uses: actions/checkout@v2
       with:
          repository: pykancha/temp
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          refs: master
          path: replied_data

     - name: Fix branches
       run: |
         cd replied_data/
         git fetch && git checkout origin/lg
         git checkout -b lg && git pull origin lg

     - name: Install Dependencies
       run: |
         cd app/link_guru/
         python -m pip install -U pip setuptools
         python -m pip install -r requirements.txt
         curl https://raw.githubusercontent.com/codelucas/newspaper/master/download_corpora.py | python

     - name: Run Tests
       id: run
       run: |
         cd app/link_guru
         source ../../personal/credentials/bots/.env 
         export NEWS_DATA='../../replied_data/link_guru/news'
         cp $NEWS_DATA/replied_to.json .
         python newsbot.py
         cp replied_to.json $NEWS_DATA/
         cp *.log $NEWS_DATA/

     - name: Commit data files
       run: |
         cd replied_data/link_guru/news/
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git pull origin lg
         git add .
         git commit -m "Updates replied ids"

     - name: Push data changes
       uses: ad-m/github-push-action@master
       with:
         github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
         directory: replied_data
         branch: lg
         repository: pykancha/temp
