name: parewa

on:
  push:
  schedule:
    - cron:  '1 */6 * * *'

jobs:
   Run:
    runs-on: ubuntu-latest

    steps:
     - name: Set up Python 3.8
       uses: actions/setup-python@v2
       with:
          python-version: 3.8

     - name: Testing repo
       uses: actions/checkout@v2
       with:
          repository: hemanta212/news_api
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: test
          path: work

     - name: Data repo
       uses: actions/checkout@v2
       with:
          repository: ssn212/ssn212.github.io
          token: ${{ secrets.SSN_ACCESS_TOKEN }}
          ref: master
          path: static_site

     - name: copy static site
       run: |
         cd work/
         cp -r ../static_site .

     - name: Poetry installation
       uses: dschep/install-poetry-action@v1.2
       with:
         version: 1.1.4

     - name: Dependencies installation
       run: |
         cd work/
         poetry run python -m pip install -U pip wheel setuptools
         git clone https://github.com/pykancha/newspaper3k_wrapper
         cd newspaper3k_wrapper
         poetry run python -m pip install -r requirements.txt
         poetry run python setup.py install
         cd ../
         poetry install
         curl -sSL https://raw.githubusercontent.com/pykancha/newspaper3k_wrapper/master/download_corpora.py -o corpora.py
         poetry run python corpora.py

     - name: Run Tests
       id: run
       run: |
          cd work/
          poetry run python ./app.py &
          while ! nc -z localhost 5000; do sleep 0.1; done; # Wait for server to start
          wget --mirror localhost:5000
          kill %1 # Kill the python server
          mv localhost:5000/ build
          poetry run python ./update_top_index.py
          mv build/top build/top_test ../static_site/
          mv build/news/* ../static_site/news/

     - name: Commit data files
       run: |
         cd static_site/
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git pull origin master
         git add .
         git commit --amend -m "Updates news data"

     - name: Push data changes
       uses: ad-m/github-push-action@master
       with:
         github_token: ${{ secrets.SSN_ACCESS_TOKEN }}
         directory: static_site
         branch: master
         force: true
         repository: ssn212/ssn212.github.io
